# Generated by Django 2.2.26 on 2022-01-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='type',
            new_name='type_house',
        ),
    ]
