# Generated by Django 2.2.26 on 2022-01-26 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0003_house_builder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('founding_documents', models.CharField(blank=True, max_length=64, null=True)),
                ('purpose', models.CharField(blank=True, max_length=64, null=True)),
                ('count_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('layout', models.CharField(blank=True, max_length=64, null=True)),
                ('residential_condition', models.CharField(blank=True, max_length=64, null=True)),
                ('all_square', models.CharField(blank=True, max_length=64, null=True)),
                ('balcony', models.CharField(blank=True, max_length=64, null=True)),
                ('heating_type', models.CharField(blank=True, max_length=64, null=True)),
                ('commission_to_agent', models.CharField(blank=True, max_length=64, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.CharField(blank=True, max_length=64, null=True)),
                ('calculation_option', models.CharField(blank=True, max_length=64, null=True)),
                ('maps', models.CharField(blank=True, max_length=64, null=True)),
                ('pub_status', models.CharField(blank=True, max_length=64, null=True)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.House')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
