# Generated by Django 2.2.26 on 2022-01-27 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0006_auto_20220127_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_filter', models.CharField(blank=True, max_length=64, null=True)),
                ('district', models.CharField(blank=True, max_length=64, null=True)),
                ('microdistrict', models.CharField(blank=True, max_length=64, null=True)),
                ('count_rooms', models.IntegerField(blank=True, null=True)),
                ('price_first', models.FloatField(blank=True, default=0, null=True)),
                ('price_last', models.FloatField(blank=True, default=0, null=True)),
                ('square_first', models.FloatField(blank=True, default=0, null=True)),
                ('square_last', models.FloatField(blank=True, default=0, null=True)),
                ('purpose', models.CharField(blank=True, max_length=64, null=True)),
                ('calculation_option', models.CharField(blank=True, max_length=64, null=True)),
                ('residential_condition', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
