# Generated by Django 2.2.26 on 2022-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_auto_20220127_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilter',
            name='price_first',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='price_last',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='square_first',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='square_last',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
