# Generated by Django 2.2.26 on 2022-01-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_flat_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.House'),
        ),
    ]
