# Generated by Django 2.2.26 on 2022-01-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_auto_20220128_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='creater',
            new_name='creator',
        ),
    ]
