# Generated by Django 2.2.26 on 2022-02-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_auto_20220201_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='reserved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
