# Generated by Django 3.2.4 on 2022-02-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_flat_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAnnouncement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/announcement')),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.announcement')),
            ],
        ),
    ]
