# Generated by Django 3.2.4 on 2022-02-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_galleryannouncement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFilter',
        ),
    ]
