# Generated by Django 3.2.4 on 2022-02-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_delete_userfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryannouncement',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminpanel.announcement'),
        ),
    ]
